=head1 NAME

ffcast - screencast an interactively selected region

=head1 SYNOPSIS

=over 4

=item B<ffcast> [<options>] [<command> [<args>]]

=back

=head1 DESCRIPTION

ffcast is a thin glue between interactive region selection and command line
tools that accept numerical geometry parameters. It makes passing geometry
parameters to command line tools as easy as a mouse click. Screencasting
tools are typical examples of such command line tools.

Typically, ffcast prompts the user to select a screen region and injects the
geometry parameters thereof into the arguments of I<E<lt>commandE<gt>>, and
then executes the resultant command line.

ffcast maintains an internal list of predefined B<sub-commands>. If
I<E<lt>commandE<gt>> matches one of them, predefined actions associated with
the matching sub-command is performed; otherwise, I<E<lt>commandE<gt>> is
executed as an external command. The B<%> sub-command can be used to prevent
I<E<lt>commandE<gt>> from being executed as a sub-command, in the case of name
conflicts.

All I<E<lt>argsE<gt>> are subject to format string substitution.
See B<L<FORMAT STRINGS|/FORMAT STRINGS>>.

If no I<E<lt>commandE<gt>> is given, a default B<ffmpeg> command line is used.

=head1 OPTIONS

Any of the I<E<lt>optionsE<gt>> can be repeated. They are parsed and applied
in the order they are specified.

=over 4

=item B<-#> I<E<lt>nE<gt>>

Select window with ID I<E<lt>nE<gt>>.

=item B<-b>

Include borders of windows to be selected.

=item B<-f>

Include window manager frame of windows to be selected.

=item B<-g> I<E<lt>geospecE<gt>>

Specify a selection in I<E<lt>geospecE<gt>>.
See B<L<GEOMETRY SPECIFICATION|/GEOMETRY SPECIFICATION>>.

=item B<-h>

Print help message, then exit.

=item B<-i>

Combine selected regions by intersection instead of union.

=item B<-l>

List predefined sub-commands with brief description, then exit.

=item B<-m> I<E<lt>nE<gt>>

Trim both dimensions of the region to be divisible by I<E<lt>nE<gt>>. By
default, both dimensions are trimmed to be divisible by C<2>, which is
required by B<x264>. A value of C<16> may help when encoding to most video
codecs. A value of C<1> disables trimming.

=item B<-p>

Print geometry of the selected region and exit without executing
I<E<lt>commandE<gt>>. The dimensions are not trimmed.

=item B<-q>

Be less verbose.

=item B<-s>

Prompt to select a region.

=item B<-v>

Be more verbose.

=item B<-w>

Prompt to select a window.

=item B<-x> I<E<lt>nE<gt>>

Select a B<Xinerama> head of ID I<E<lt>nE<gt>>. Multiple heads can be
specified either as a comma-separated list, or by repeating this option. Use
C<list> to get a list of head IDs and the corresponding geometry parameters.

=back

=head1 FORMAT STRINGS

The following format strings are supported:

=over 4

=item B<%d>

B<DISPLAY>

=item B<%h>

Height

=item B<%w>

Width

=item B<%x>

Left offset

=item B<%y>

Top offset

=item B<%X>

Right offset

=item B<%Y>

Bottom offset

=item B<%c>

Equivalent to B<%x,%y>

=item B<%C>

Equivalent to B<%X,%Y>

=item B<%g>

Equivalent to B<%wx%h+%x+%y>

=item B<%s>

Equivalent to B<%wx%h>

=item B<%%>

A literal %

=back

=head1 GEOMETRY SPECIFICATION

A I<E<lt>geospecE<gt>> specifies a geometry in one of the following forms:

=over 4

=item S<I<x>B<,>I<y> I<X>B<,>I<Y>>

I<x>, I<y>, I<X> and I<Y> are the left, top, right and bottom offsets,
respectively.

=item I<w>B<x>I<h>B<+>I<x>B<+>I<y>

I<w>, I<h>, I<x> and I<y> are the width, height and left and right offsets,
respectively.

=back

=head1 EXAMPLES

Use the sub-command B<png> to take a screenshot of a window, including its
window manager frame:

    ffcast -fw png screenshot-%s.png

Screencast fullscreen on display C<:1>, using the default B<ffmpeg> command
line, with debug messages:

    DISPLAY=:1 ffcast -vv

Screencast all three windows of B<GIMP>:

    ffcast -www ffmpeg -f x11grab -show_region 1 -s %s -i %d+%c out.mp4

Resize a window to the same size as another, by two mouse clicks:

    ffcast -w xdotool selectwindow windowsize %w %h windowfocus

Take a screenshot of two windows combined, excluding anything invisible on
head 0, using either of:

    ffcast -i -x 0 -g "$(ffcast -wwp)" png
    ffcast -m 1 -ww ffcast -i -x 0 -g %g png

=head1 AUTHOR

lolilolicon E<lt>lolilolicon@gmail.comE<gt>

=head1 SEE ALSO

B<ffmpeg(1)>, B<X(7)>

=for comment
vim:ft=pod:spell:spelllang=en_us:cc=78:

=cut
