FFcast
======

NOTE: Users of FFcast 1.0 will have to update their command lines. See issue #8.

FFcast helps the user interactively select a screen region and hands over the
geometry to an external command, such as FFmpeg, to record a screencast, or
take a screenshot, among other things.

FFcast is a historical name. To say "FFcast wraps around FFmpeg" is as good as
saying "XBMC runs on Xbox". Sure, FFmpeg is a fine thing to wrap around, but
FFcast can wrap around a lot of things.

FFcast really is a "handy" or "human friendly" interface for anything involving
selecting a box on the screen. In the same spirit, it tries to provide handy
terse commands for common tasks, and allows users to define their own commands,
in a straight-forward manner, to tailor to their own needs.

Requirements
------------

.FFcast

  * Bash 4.3+
  * FFmpeg   - for some sub-commands (`png`, `rec`)
  * xdpyinfo - for the `-x` option
  * xprop    - for the `-f` option
  * xrectsel - for the `-s` option (included)
  * xwininfo - for the `-w` option

.xrectsel

  * libX11

Get the Source
--------------

The source code is hosted at GitHub:
either https://github.com/lolilolicon/FFcast.git[git clone] or
https://github.com/lolilolicon/FFcast/releases[get releases].

Installation
------------

To build and install from source,

  ./bootstrap  # required if ./configure is not present
  ./configure --prefix /usr --libexecdir /usr/lib --sysconfdir /etc
  make
  make DESTDIR="$directory" install

Arch Linux users can simply install
https://aur.archlinux.org/packages/ffcast/[AUR/ffcast].

Usage
-----

See +ffcast(1)+.

////
vim:ts=2:sw=2:syntax=asciidoc:et:spell:spelllang=en_us:cc=80:
////
